### PR TITLE
Bug/memory

### LINKED ISSUE #326: 🐞 Nuget Package Leaking memory
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Defect ID : 15986
ElectionGuard: Scan ran out of resources and system alerted after scanning just 117 ballots

**Description**

ElectionGuard: Scan ran out of resources and system alerted after scanning just 117 ballots 
Setup: 
1.	Election used was the County single-sheet 
2.	LAT was printed 3 times for volume testing
3.	Scan all of the ballots from all 3 LAT sets
Expected Results: 
1.	All ballots can be scanned and cast without issue
Actual Results: 
1.	System Alert - In order to continue using this machine, the system resources need to be refreshed
2.	This alert occurred after scanning only 117 ballots.  
Impact: 
1.	Very High - voter facing and occurs way too often - looks bad to have a Scan error and need rebooting this often
Legacy:  This error usually only occurs after scanning thousands of ballots and is unlikely to be seen in previous versions of Verity.  Also, for an election of this size (small) we should not see this error 

**Defect Details**

Defect ID	15986
Status	New
Project	Scan
Subject	Saving Data
Reproducible	Y
Severity	4-Very High
Priority	5-Urgent
Detected on Date	2022-08-26
Defect Type	Product Defect
Modified	2022-08-26 10:31:56
Detected in Release	ElectionGuard
Detected in Cycle	Drop 5
Target Release	ElectionGuard

### Expected Behavior

All ballots can be scanned and cast without issue

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SteveMaier-IRT**
### Issue

Fixes #326 

### Description
Memory was leaking when ballots were being encrypted and cast/spoiled.

### Testing
Added C++ and .NET tests to test creating 10000 submitted ballots without running out of memory.

### CODE REVIEW

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/NativeInterface.cs [hunk 1]
```diff
@@ -2793,7 +2793,7 @@ internal class PlaintextBallotHandle
                 [ReliabilityContract(Consistency.WillNotCorruptState, Cer.MayFail)]
                 protected override bool Free()
                 {
-                    if (IsClosed) return true;
+                    if (IsFreed) return true;
```
Comment (SteveMaier-IRT) [inline bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/NativeInterface.cs:2796]: For the ballot classes, it was thinking that the handle had been closed already and so it never tried to free the unmanaged pointer for it.  Changed to a new variable that can be controlled instead of one from the base class.

**Review by lprichar — APPROVED** [review]
WELL DONE!!
