### PR TITLE
When creating placeholders set the IsPlaceholder to true.

### LINKED ISSUE #316: 🐞 Validation Error with Placeholders
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Placeholders are not being set correctly in the encrypted ballots.  The placeholders always had flags that said that the IsPlaceholder value is false, even when it should be true;

### Expected Behavior

For true placeholders, the value should be returned as true instead of false.

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SteveMaier-IRT**
Unit test added to make sure the value is read properly.

### Issue
*Link your PR to an issue*

Fixes #316 

### Description
During encryption the placeholders will getting a flag set to false to tell that they were placeholders.

### Testing
C++ unit test added to make sure things failed and then passed.

### CODE REVIEW

File: test/electionguard/test_encrypt.cpp [hunk 1]
```diff
@@ -473,3 +473,27 @@ TEST_CASE("Create EncryptionMediator with different manifest hash")
...
+    auto context = ElectionGenerator::getFakeContext(*internal, *keypair->getPublicKey());
+    auto device = make_unique<EncryptionDevice>(12345UL, 23456UL, 34567UL, "Location");
+
+    auto ballot = BallotGenerator::getFakeBallot(*internal);
+
+    // Act
+    auto ciphertext = encryptBallot(*ballot, *internal, *context, *device->getHash());
+
+    // Assert
+    // TODO: compare other values
```
Comment (lprichar) [inline test/electionguard/test_encrypt.cpp:493]: ?

**Review by lprichar — APPROVED** [review]
lgtm
