### PR TITLE
fix crash on overvote

### LINKED ISSUE #227: 🐞 fix segv when encrypting a ballot with overvotes in c#
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

it crashes

### Expected Behavior

it doesnt

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AddressXception**
[//]: # (🚨 Please review the CONTRIBUTING.md in this repository. 💔Thank you!)

### Issue
*Link your PR to an issue*

Fixes #227 

### Description
do not crash when calling encrypt from c# with a ballot that has an overvote. instead, throw an exception. This PR also includes some groundwork for #183 

### Testing
1. `make test-netstandard`

### CODE REVIEW

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/Encrypt.cs [hunk 1]
```diff
@@ -31,10 +31,7 @@ public class EncryptionDevice : DisposableBase
         {
             var status = NativeInterface.EncryptionDevice.New(
                 deviceUuid, sessionUuid, launchCode, location, out Handle);
-            if (status != Status.ELECTIONGUARD_STATUS_SUCCESS)
-            {
-                Console.WriteLine($"EncryptionDevice New Error Status: {status}");
-            }
+            status.ThrowIfError();
```
Comment (AddressXception) [inline bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/Encrypt.cs:34]: this should be applied anywhere the status is checked, but only did it in files i was already touching for now

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/NativeInterface.cs [hunk 2]
```diff
@@ -18,6 +18,37 @@ internal enum Status
         /// This code should always be the last code in the collection
         // so that the status codes string can be correctly derived
         ELECTIONGUARD_STATUS_UNKNOWN
+
+
+    }
+
+    static internal class StatusExtensions
```
Comment (AddressXception) [inline bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/NativeInterface.cs:25]: i left this here right next to the enum because it needs to be updated if the enumeration changes at all and i figured it would be easy to miss if it was in its own file.

File: test/electionguard/generators/manifest.hpp [hunk 3]
```diff
@@ -11,21 +11,34 @@
 using namespace electionguard;
 using namespace std;
 
-namespace electionguard::test::mocks
+#ifndef TEST_SPEC_VERSION
+#    define TEST_SPEC_VERSION "0.95.0"
+#endif
+
+#ifndef TEST_USE_SAMPLE
+#    define TEST_USE_SAMPLE "hamilton-general"
```
Comment (AddressXception) [inline test/electionguard/generators/manifest.hpp:19]: should probably be runtime configurable and not compile time configurable

File: Makefile [hunk 4]
```diff
@@ -58,6 +58,9 @@ ifeq ($(OPERATING_SYSTEM),Windows)
 	choco install wget
 endif
 	wget -O cmake/CPM.cmake https://github.com/TheLartians/CPM.cmake/releases/latest/download/CPM.cmake
+	wget -O sample-data.zip https://github.com/microsoft/electionguard/releases/download/v0.95.0/sample-data.zip
+	unzip sample-data.zip
```
Comment (SteveMaier-IRT) [inline Makefile:62]: you might want to add a -o to this to allow the files to overwrite a previous download.  This is what is cause the build issue

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Tests/TestEncrypt.cs [hunk 5]
```diff
@@ -51,6 +53,46 @@ public void Test_Encrypt_Ballot_Simple_Succeeds()
...
+        public void Test_Encrypt_Ballot_Undervote_Succeeds()
+        {
+            // Configure the election context
+            var keypair = ElGamalKeyPair.FromSecret(Constants.TWO_MOD_Q);
+            var manifest = ManifestGenerator.GetJeffersonCountyManifest_Minimal();
+            var internalManifest = new InternalManifest(manifest);
+            var context = new CiphertextElectionContext(
+                1UL, 1UL, keypair.PublicKey, Constants.TWO_MOD_Q, internalManifest.ManifestHash);
+            var device = new EncryptionDevice(12345UL, 23456UL, 34567UL, "Location");
+            var mediator = new EncryptionMediator(internalManifest, context, device);
```
Comment (lprichar) [inline bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Tests/TestEncrypt.cs:66]: That's a lot of copy and pasting between the setup of these two tests.  I personally prefer in these cases to use helper methods with descriptive names to help make tests human readable ala Clean Code, almost like making a DSL per test file.  That's because I prefer to view tests as documentation first that's executable and verifiable second.  FWIW I've read over these tests a few times and I don't understand what they're saying.  So, if getting the tests understandable by someone with my minimal level of understanding is the objective, then they fail.  But that can be a lot of work, and with a looming deadline it may not be worth it.

File: test/electionguard/generators/manifest.hpp (hunk 3 above)
Comment (lprichar) [reply test/electionguard/generators/manifest.hpp:19]: Same for the `election_manifest_jefferson_county.json` below?

**Review by SteveMaier-IRT — APPROVED** [review]

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Tests/TestEncrypt.cs (hunk 5 above)
Comment (AddressXception) [reply bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Tests/TestEncrypt.cs:66]: https://github.com/microsoft/electionguard-cpp/issues/229

**Comment by colleenirt** [comment]
@SteveMaier-IRT should this be in the closed column?
